name = "terabox-dl"
compatibility_date = "2023-01-01"

[site]
bucket = "./src/page"

[vars]
JS_TOKEN = "5FC6A38CA91FF9C62C03B21E601F4AE347C1EFBEE091C299D3F556F69D526FE85A6F2FFBFE1CF32CCA2734F337E20E6F1C6A5E085004657CBB16B26FC9804C7D"
DP_LOGID = "92644000694221630014"
COOKIES = "browserid=V5o41vWgeqjjX5OeOgjTAnKQrdBJF1nLjADEh1DOQGOhr9Z_b8dJLWmpxL8=; lang=vi; __bid_n=188cf37b387fbd7fb04207; _ga=GA1.1.957455348.1687339985; ndus=Yy1ZDC7teHuiw56Ni1vKahIzvSMsZ9r0WPxLAYtp; TSID=95p6S0wTwPvbIo310FpbYN21dL9ovsFk; dom3ic8zudi28v8lr6fgphwffqoz0j6c=cab757f0-d775-4664-b713-4a0f7589895a%3A1%3A1; _gcl_au=1.1.934000585.1687953494; _fbp=fb.1.1687953494841.1055651565; _tt_enable_cookie=1; _ttp=eT7K42zRChQnenE1MuDFDAwpSxT; _ga_RSNVN63CM3=GS1.1.1687960182.2.0.1687960182.60.0.0; csrfToken=kNLR5WboF7Rluz65Dpth00m3; PANWEB=1; ndut_fmt=C603A221DED08C0DA3B4714207670675ACF05A927C87C1AF3B73B2ED061C3B00; ab_sr=1.0.1_OWU1MThmOTQ0ZDQ1ODFkNDk5YmI5ODQ4NDRmMTQ5ODRmMzliZjQzNGFhOTI5NDgwYmIyYzcxYmFhY2U5MmI1NTMzMzUwNGVhN2FjNmVlMDZhNGUyMmM4NjFkMWQxZWI1OGY2NDIxYWY0OGJmYjZiZDUzMjg0NjNkMzQzMjMzYTJlZmRlNWY4ZDhlMzNiZWRhNDlhNzY3ZDM5MTUyMWExZg==; _ga_06ZNKL8C2E=GS1.1.1688117823.12.1.1688117829.54.0.0"

